#+title: Introduction Draft

Overall, input variables such as the sowing/harvesting date, irrigation status, and the initial variables will be adapted in accordance to the experimental data.
The weather inputs for this study will be derived from daily maximum/minimum temperature, rainfall, and solar radiation, in which the data will be provided by NASA POWER. 
Additionally, the atmospheric CO2 concentration will be assumed to be 420 ppm, in accordance to the global average values of the Mauna Loa Observatory at the time of the experiments. 
Lastly, the soil type input for this study is to be determined by referring to the Unified Soil Classification System Pyramid that best characterizes the common soil type of the Cerrado region. 


Taking such backgrounds into consideration, the experimental sites of Rio Paranaíba, Viçosa, São Gotardo, Sete Lagoas, and Itutinga will be explored for this study. 
This accounts for the application of irrigation treatments and biotic stress responses that the field experiments were previously exposed to. 
Namely, the wheat cultivar strain BRS264 will be addressed in this study, as it was widely applied to research irrigation treatments under varying seasonal conditions. 
Additionally, it is to be noted that converntional wheat cultivation favors mild air temperatures. Therefore, the selected locations of the Cerrado are to be situated in high altitude regions.
