#+title: Simulation of wheat yield in the Cerrado region of Southern Brazil using the SIMPLE crop model

* Introduction
The Cerrado region of Brazil refers to the tropical savanna biomes that are widely distributed in the Eastern states of the country. Overall, the climate of Cerrado region is characterized by the semi humid tropical regimes that are dominated by wet and cold seasons annually. Conventionally, Brazil’s wheat production is dependent on the Southern regions of Brazil, contributing up to 91 % of national production in 2017. Although not considered a traditional region of cereal production, the Cerrado has become the target of agricultural expansion since the 1980s, due to its potential to grow wheat in the off-season from that of the Southern regions. Hence, the incentivization of the Cerrado in crop production is considered a lucrative development in the region, partitioning approximately 44% of its total area to farmland. However, Brazil’s agroeconomic reliance on such expansions may highlight the increasing vulnerability to climate change, which could destabilize crop production in the fulfilment of domestic food demand.

here is where the second paragraph goes...

* Data and Methods
** Experimental Data
Information about experimental set ups. Water managment? Nitrogen (eventhough not used in the SIMPLE model). Average sowing and harvest date. Information on the cultivar BRS264?

** SIMPLE model

* Results
** Simulated experiments
In order to assess the capabilities of the SIMPLE model to model wheat growth in the Cerrado region, we simulated yield for 13 field trials in 5 different locations. Irrigated location where simulated with no water stress, implying a perfect watering routine. Nonirrigated crops had water stress turned on and relied only on rainfalls, supplied in the weather data. Since no nutrients are simulated in the SIMPLE model, we assume perfect nutrient saturation of the crops, a state not uncommon for field trials. The atmospheric CO2 concentration was set to 415 ppm, reflecting the current value as of 2020.
The model parameters were derived from literature or estimated. (cite zhao et al.) Further calibrated was done by adjusting cultivar parameters (Tsum, I50A, I50B and HI) in reasonable levels.

(insert table here.)

The results of the simulation across experiments are shown in (Figure calibration). The model has an accuracy of: (statistics here.)

The first thing one can note about the results is that in many cases there is significant deviation between the simulated and observed yield. While several experiments are accurately simulated, a general trend of the simulation to significantly overestimates the observed yield can be observed. Due to the simple nature of the model this is to be expected, since in reality there are many more yield-limiting factors, such as nutrients, that the SIMPLE model does not account for. Therefore we should not be surprised by the systematic overestimation of yield.

We also observe that the accuracy of predicting yield varies between locations, as can  be expected between differing environments. It can be seen, that experiments conducted in Vicosa, MG have the best simulated results of all 5 locations. On the other hand, specifically the nonirrigated field trials in Sao Gotardo, which also have been inoculated with a fungal pathogen, show a bad fit between simulated and observed yield, by grossly overestimating the yield in the simulation. The inability of the SIMPLE model to predict the the yield accurately in this case is again due its simplicity, as pest and diseases are among the factors not accounted for.


Calibration of model with the obserevd data from the experiments. What locations worked well, which ones did not work so well? Results by groups? What was done during calibration?

** Climate change prediction
Work out results for climate change data simulations. Depending on how much time we have.

* Discussion
