#+title: Project Outline

* Organization
1. Organization (Run SIMPLE)
2. Calibration (stats) --> *plots*
3. Application --> *plots*

* Running Tasks
- [ ] Download weather data from NASA power of all locations.
- [ ] Get the model running woth experimental data

* Data
_Data necessary to run the SIMPLE model:_
- weather (download from NASA)
- soil (*Where is the soil data?*)
- crop management (supplied)

  Files so far in /data//:
  - /location-info.xlsx/ - Location info for experimental location.
  - /dataset-BRS_264-MN-1209.xlsx/ - Expermimental crop from locations.



** Experimental Data
The SIMPLE model is calibrated with for this data. Optimal conditions (no disease, pest, nutrient deficiency)

= Cultivar and species parameters (When adjusting do so in respective order)

*  Calibration of the SIMPLE model with wheat data from the /Cerrado/ in Brazil
Simulate wheat in Cerrado. How much wheat do we really get?

How will we calibrate? Using subsets of the data? Sensitivity Analysis?

* Model Application
relevant data to run the simple model in a chosen condition and context of a hypothesis.

Application to climatic scenarios from IPCC. WHat happens with the wheat yield.
* Wheat Infos
Download weather data from NASA power.
Experiment provided by Rogerio.
Clone this git repository on local machine
