#+title: Project Outline

*** General Information
URL of this repository: [[https://github.com/pwolper/SIMPLE-project.git]]

For more infromation on how to connect with Git and GitHub from RStudio see /doc/Connect-Git-and-RStudio.org/.

* Organization
1. Organization (Run SIMPLE)
2. Calibration (stats) --> *plots*
3. Application --> *plots*

* Running Tasks
- [ ] finish calibration
- [ ] plot outlier weather data, compare them to experiment with good predition.
- [ ] Find out more information about the experimental setup, ie. fungal inoculations we dont't know about
- [ ]
* Data
_Data necessary to run the SIMPLE model:_
- weather (download from NASA)
- soil (*Find soil data from NASA power or SoilGrids*)
- crop management (supplied)

  Files so far in /data//:
  - /location-info.xlsx/ - Location info for experimental location.
  - /dataset-BRS_264-MN-1209.xlsx/ - Expermimental crop from locations.

** Data files to use:
- Species Parameters.csv
- Cultivar.csv
  Species parameters already set! Test sensitivity.
- Soil.csv
  Which soil can we use? Firgure out the soil characteristics of soil in the Brazilian Cerrado and compare to soils found in soil.csv
- Treatment.csv
- Simulation managment.csv
To turn on and off simulations.

** Experimental Data
The SIMPLE model is calibrated with for this data. Optimal conditions (no disease, pest, nutrient deficiency)
= Cultivar and species parameters (When adjusting do so in respective order)

Experimental Data:

| Year | Location       | Trt | Water | Name                 |
| 2018 | Rio Paranaiba  |   1 | no    | RIOPA_18_irrigated   |
| 2019 | Rio Paraneiba  |   2 | no    | RIOPA_19_irrigated   |
| 2019 | Vicosa         |   3 | no    | VICO_19_irrigated    |
| 2020 | Vicosa         |   4 | no    | VICO_20_irrigated    |
| 2020 | Vicosa         |   5 | yes   | VICO_20_nonirrigated |
| 2021 | Vicosa         |   6 | no    | VICO_21_irrigated    |
| 2020 | Sao Gotardo    |   7 | no    | SAOG_20_irrigated    |
| 2020 | Sao Gotardo*   |   8 | yes   | SAOG_20_nonirrigated |
| 2021 | Sao Gotardo    |   9 | no    | SAOG_21_irrigated    |
| 2021 | Sao Gotardo(*) |  10 | yes   | SAOG_21_nonirrigated |
| 2022 | Sao Gotardo(*) |  11 | yes   | SAOG_22_nonirrigated |
| 2020 | Sete Lagoas    |  12 | no    | SETE_20_irrigated    |
| 2021 | Itutinga       |  13 | yes   | ITUT_21_nonirrigated |

*according to Casagrande et al. 2023, this location was inoculated with blast fungus.

*** Casagrande et al., (2023)
Information to the experiments can be found here:
[[cite:&casagrande-2023-new-brazil]]

Casagrande, C. R., Mezzomo, H. C., Santos, C. V. d., Sousa, D. J. P. s.,
Yamanaka, C. H., Olivoto, T., Kaio Olimpio das Gra\ccas Dias, … (2023). New
agricultural wheat frontier in brazil: envirotypes applied in the adaptability
and stability of wheat genotypes in contrasting environments.
http://dx.doi.org/10.21203/rs.3.rs-2415885/v1

*  Calibration of the SIMPLE model with wheat data from the /Cerrado/ in Brazil
Simulate wheat in Cerrado. How much wheat do we really get?

Ideas: Show the results of the simulation by location if it is easier to interpret. Or by year. Potentially in a matrix?

Values adjusted during calibration:
| Paramter      | initial |  new |
| Cultivar/HI   |    0.36 | 0.34 |
| Cultivar/I50A |     450 |  500 |
| Cultivar/I50B |     250 |  300 |

** Parameters that could be adusted
- Tbase. Casagrande et al. used 5 degrees celcius?
  Leads to worse results though.


** Soil
Either take soils from the simple model. Research which soil would be the best.

Or use online data to estimate parameters ourselves.
eg. AWC = (FC - WP)/10 * BD
[FC WP] - Estimation from soil texture.
% Clay Sand % pedotransfer equation

_Soil content in the Cerrado:_
- median percentage:
  Sand, Silt, Clay : 48.6, 15.3, 33.5
from:https://www.sciencedirect.com/topics/agricultural-and-biological-sciences/cerrado-soils

On Soil Pyramid: Sandy loam1 or similar?

*** Pedotransfer equations.
Can we use them for more exact soil modeling?

* Model Application
Relevant data to run the simple model in a chosen condition and context of a hypothesis.

Application to climatic scenarios from IPCC. What happens with the wheat yield.

Worth reading:
- Junior, R. d. S. N., Martre, P., Finger, R., Velde, M. v. d., Ben-Ari, T.,
  Ewert, F., Webber, H., … (2021). Extreme lows of wheat production in brazil.
  Environmental Research Letters, 16(10), 104025.
  http://dx.doi.org/10.1088/1748-9326/ac26f3

** Discussion
Describe and discuss results. First describe the calibration results. Then continue with application results.
Why does out simulation fail in some places? Can we explain it with weather or possibly other reasons?

*** Plot of the outlier location weather data.
compare to weather during good prediction season.

**** Outlier locations
Overestimation of Simulation to observed yield:

Top 3 outliers:
1. SAOG_20_nonirrigated: *overestimation*
2. SAOG_21_nonirrigated: *overestimation*
3. SETE_20_irrigated: *overestimation*

Blast Fungus inocultation for SAOG_21/22_nonirrigated as well? Was the non-irrigated experiment in Sao Gotardo always inoculated with fungi?
What happend for Sete Lagos? Different weather that year?

** RCP85 Climate Prediction
*** TODO Add Climate data to repository
