#+title: Project Outline

*** General Information
URL of this repository: [[https://github.com/pwolper/SIMPLE-project.git]]

For more infromation on how to connect with Git and GitHub from RStudio see /doc/Connect-Git-and-RStudio.org/.

* Organization
1. Organization (Run SIMPLE)
2. Calibration (stats) --> *plots*
3. Application --> *plots*
teeeeest

* Running Tasks
- [ ] Download weather data from NASA power of all locations.
- [ ] Get the model running with experimental data for everybody.
- [ ] Merge experimental data for Cerrado with /SIMPLE/Input/.
- [ ] Get soil data

* Data
change
_Data necessary to run the SIMPLE model:_
- weather (download from NASA)
- soil (*Find soil data from NASA power or SoilGrids*)
- crop management (supplied)

  Files so far in /data//:
  - /location-info.xlsx/ - Location info for experimental location.
  - /dataset-BRS_264-MN-1209.xlsx/ - Expermimental crop from locations.

** Soil
Either take soils from the simple model. Research which soil would be the best.

Or use online data to estimate parameters ourselves.
eg. AWC = (FC - WP)/10 * BD
[FC WP] - Estimation from soil texture.
% Clay Sand % pedotransfer equation

Soil parameter RDZ can be calibrated if S_Water is not enough.

** Experimental Data
The SIMPLE model is calibrated with for this data. Optimal conditions (no disease, pest, nutrient deficiency)

= Cultivar and species parameters (When adjusting do so in respective order)

*  Calibration of the SIMPLE model with wheat data from the /Cerrado/ in Brazil
Simulate wheat in Cerrado. How much wheat do we really get?

How will we calibrate? Using subsets of the data? Sensitivity Analysis?

* Model Application
relevant data to run the simple model in a chosen condition and context of a hypothesis.

Application to climatic scenarios from IPCC. WHat happens with the wheat yield.

** Discussion
Describe and discuss results. First describe the calibration results. Then continue with application results.
