#+title: Project Outline

*** General Information
URL of this repository: [[https://github.com/pwolper/SIMPLE-project.git]]

For more infromation on how to connect with Git and GitHub from RStudio see /doc/Connect-Git-and-RStudio.org/.

* Organization
1. Organization (Run SIMPLE)
2. Calibration (stats) --> *plots*
3. Application --> *plots*

* Running Tasks
- [X] Download weather data from NASA power of all locations.
- [ ] Get the model running with experimental data
- [-] Merge experimental data for Cerrado with /SIMPLE/Input/.
- [X] Get soil data

* Data
_Data necessary to run the SIMPLE model:_
- weather (download from NASA)
- soil (*Find soil data from NASA power or SoilGrids*)
- crop management (supplied)

  Files so far in /data//:
  - /location-info.xlsx/ - Location info for experimental location.
  - /dataset-BRS_264-MN-1209.xlsx/ - Expermimental crop from locations.

** Data files to use:
- Species Parameters.csv
- Cultivar.csv
  Species parameters already set! Test sensitivity.
- Soil.csv
  Which soil can we use? Firgure out the soil characteristics of soil in the Brazilian Cerrado and compare to soils found in soil.csv
- Treatment.csv
- Simulation managment.csv
To turn on and off simulations.

** Experimental Data
The SIMPLE model is calibrated with for this data. Optimal conditions (no disease, pest, nutrient deficiency)
= Cultivar and species parameters (When adjusting do so in respective order)

Experimental Data:

| Year | Location      | Trt | Water | Name                 | status  |
| 2018 | Rio Paranaiba |   1 | no    | RIOPA_18_irrigated   | works   |
| 2019 | Rio Paraneiba |   2 | no    | RIOPA_19_irrigated   | missing |
| 2019 | Vicosa        |   3 | no    | VICO_19_irrigated    | works   |
| 2020 | Vicosa        |   4 | no    | VICO_20_irrigated    | works   |
| 2020 | Vicosa        |   5 | yes   | VICO_20_nonirrigated |         |
| 2021 | Vicosa        |   6 | no    | VICO_21_irrigated    | works   |
| 2020 | Sao Gotardo   |   7 | no    | SAOG_20_irrigated    | works   |
| 2020 | Sao Gotardo   |   8 | yes   | SAOG_20_nonirrigated |         |
| 2021 | Sao Gotardo   |   9 | no    | SAOG_21_irrigated    | works   |
| 2021 | Sao Gotardo   |  10 | yes   | SAOG_21_nonirrigated |         |
| 2022 | Sao Gotardo   |  11 | yes   | SAOG_22_nonirrigated |         |
| 2020 | Sete Lagoas   |  12 | no    | SETE_20_irrigated    | works   |
| 2021 | Itutinga      |  13 | yes   | ITUT_21_nonirrigated |         |

Plot the locations on a map? Using cartopleth package or similar. Check out rgraph gallery for inspiration.

*  Calibration of the SIMPLE model with wheat data from the /Cerrado/ in Brazil
Simulate wheat in Cerrado. How much wheat do we really get?

How will we calibrate? Using subsets of the data? Sensitivity Analysis?

Ideas: Show the results of the simulation by location if it is easier to interpret. Or by year. Potentially in a matrix?

_First Model simulation, 30.01.23_
Using RIOPA_2018 the model simulates an actual yield very close to that measured RMSE = 2,5%

** Cultivar
Parameters to use for calibration. S_WATER (initially 0.4, changed to what?)

** Soil
Either take soils from the simple model. Research which soil would be the best.

Or use online data to estimate parameters ourselves.
eg. AWC = (FC - WP)/10 * BD
[FC WP] - Estimation from soil texture.
% Clay Sand % pedotransfer equation

_Soil content in the Cerrado:_
- median percentage:
  Sand, Silt, Clay : 48.6, 15.3, 33.5
from:https://www.sciencedirect.com/topics/agricultural-and-biological-sciences/cerrado-soils

On Soil Pyramid: Sandy loam1 or similar?

*** Pedotransfer equations.
Can we use them for more exact soil modeling?

* Model Application
Relevant data to run the simple model in a chosen condition and context of a hypothesis.

Application to climatic scenarios from IPCC. WHat happens with the wheat yield.

Worth reading:
- Junior, R. d. S. N., Martre, P., Finger, R., Velde, M. v. d., Ben-Ari, T.,
  Ewert, F., Webber, H., … (2021). Extreme lows of wheat production in brazil.
  Environmental Research Letters, 16(10), 104025.
  http://dx.doi.org/10.1088/1748-9326/ac26f3


** RCP85 Climate Prediction

** Discussion
Describe and discuss results. First describe the calibration results. Then continue with application results.
Why does out simulation fail in some places? Can we explain it with weather or possibly other reasons?

*** Plot of the outlier location weather data.
compare to weather during good prediction season.

**** Outlier location
Overestimation of Simulation to observed yield:
- SAOG_20_nonirrigated: *strong overestimation*
