#+title: Project Outline

*** General Information
URL of this repository: [[https://github.com/pwolper/SIMPLE-project.git]]

For more infromation on how to connect with Git and GitHub from RStudio see /doc/Connect-Git-and-RStudio.org/.

* Organization
1. Organization (Run SIMPLE)
2. Calibration (stats) --> *plots*
3. Application --> *plots*

* Running Tasks
- [ ] Download weather data from NASA power of all locations.
- [ ] Get the model running with experimental data
- [ ] Merge experimental data for Cerrado with /SIMPLE/Input/.
- [ ] Get soil data

* Data
_Data necessary to run the SIMPLE model:_
- weather (download from NASA)
- soil (*Find soil data from NASA power or SoilGrids*)
- crop management (supplied)

  Files so far in /data//:
  - /location-info.xlsx/ - Location info for experimental location.
  - /dataset-BRS_264-MN-1209.xlsx/ - Expermimental crop from locations.

** Data files to use:
*** [ ] Cultivar.csv
Which cultivar to use? Yecorea Rojo? Batten? Possibly other?
*** [ ] Species Parameters.csv
Species parameters already set! Test sensitivity.
*** [ ] Irrigation.csv
What amount of water is irrigated? What means dry? What data can we supply for the Irrigation.csv?
*** [ ] Soil.csv
Which soil can we use? Firgure out the soil characteristics of soil in the Brazilian Cerrado and compare to soils found in soil.csv
*** [ ] Treatment.csv
Fill out the treatment information. InitialBio? InitialFsolar? InitialTT?
*** [ ] Simulation managment.csv


** Soil
Either take soils from the simple model. Research which soil would be the best.

Or use online data to estimate parameters ourselves.
eg. AWC = (FC - WP)/10 * BD
[FC WP] - Estimation from soil texture.
% Clay Sand % pedotransfer equation

Soil: sand should be chosen
SAND: 0.4.


** Experimental Data
The SIMPLE model is calibrated with for this data. Optimal conditions (no disease, pest, nutrient deficiency)

= Cultivar and species parameters (When adjusting do so in respective order)

*  Calibration of the SIMPLE model with wheat data from the /Cerrado/ in Brazil
Simulate wheat in Cerrado. How much wheat do we really get?

How will we calibrate? Using subsets of the data? Sensitivity Analysis?

* Model Application
relevant data to run the simple model in a chosen condition and context of a hypothesis.

Application to climatic scenarios from IPCC. WHat happens with the wheat yield.

Worth reading:
de Souza Noia Junior et al. 2021 ERL.
** Discussion
Describe and discuss results. First describe the calibration results. Then continue with application results.
