#+title: Connect Git And R Studio

This set of instructtions was generated with the help of ChatGPT by OpenAI on <2023-01-11 Mi>

* How to connec RStudio with Git:

1) Install Git on your computer by downloading the appropriate installer from the official website (https://git-scm.com/downloads).

2) Open RStudio and go to the "Global Options" menu, located under the "Tools" menu.

3) Select "Git/SVN" from the options on the left and then provide the path to the Git executable in the "Git executable" field. If Git is correctly installed, this should be filled in automatically by RStudio.

4) Once the above steps have been completed, you can create a new project in RStudio and select "Version Control" and then "Git".

5) Provide the URL of the GitHub repository you want to clone and select a local directory where you want to save the cloned repository.

6) Press 'create project' and wait for the repository to be cloned and to be loaded into Rstudio.

7) You should now have a local copy of the repository on your machine, and you can start making changes, committing them, and pushing them back to the remote repository on GitHub.

** Commands to move files to GitHub
This workflow can be done from RStudios graphical UI or alternatively from the Command line using the below commands:

To add files to the repository, use the command *git add <filename>* or *git add .* to add all files
To commit the changes use the command *git commit -m "message"* and using a sensible commit message is encouraged.
To push the changes to a remote repository use the command *git push <remote> <branch>*. Or just *git push*.
